# Numpy 🧮 i Pytorch 🔥

## 🎯 Cel zajęć

Celem laboratorium jest przypomnienie podstaw pracy z biblioteką NumPy oraz poznanie elementarnych operacji w PyTorch, które będą fundamentem dalszej pracy z sieciami neuronowymi.

# 🧮 NumPy – powtórzenie

NumPy udostępnia strukturę `ndarray`, która:

* przechowuje dane jednego typu
* jest szybka dzięki ciągłemu układowi w pamięci
* pozwala na wektoryzację obliczeń


```bash
pip install numpy
```

```python
import numpy as np
```

---

## ✅ Podstawowe atrybuty tablicy

```python
a = np.array([0, 1, 2, 3])

print(type(a))
print(a.dtype)
print(a.shape)
print(a.ndim)
```

### 📘 Teoria

* `type(a)` → typ obiektu (ndarray)
* `dtype` → typ danych (np. int64)
* `shape` → wymiary tablicy
* `ndim` → liczba wymiarów

---

## ✅ Operacje element‑po‑elemencie

```python
a = np.array([1, 2, 3, 4])
b = np.array([2, 3, 4, 5])

print(a + b)
print(a * b)
print(a ** b)
```

### 📘 Teoria

NumPy domyślnie wykonuje operacje **element‑wise**:

[ c_i = f(a_i, b_i) ]

---

## ✅ Tablice wielowymiarowe

```python
a = np.array([[0, 1, 2, 3],
              [10, 11, 12, 13]])

print(a.shape)
print(a.size)
print(a.ndim)
print(a[1])
```

### 📘 Teoria

* `shape` → (wiersze, kolumny)
* `size` → liczba wszystkich elementów
* `a[1]` → drugi wiersz

---

## ✅ Indeksowanie i slicing

```python
a = np.array([10, 11, 12, 13, 14])

print(a[1:3])
print(a[1:-2])
print(a[:3])
print(a[-2:])
print(a[::2])
```

### 📘 Teoria

Slicing: `[start:stop:step]`

---

## ⚠️ Widoki vs kopie danych

```python
a = np.array([0, 1, 2, 3, 4])

b = a[2:4]
b[0] = 10

print(a)
print(b)
```

### 📘 Teoria

Slicing tworzy **widok**, nie kopię → zmiany wpływają na oryginał.

---

## ✅ Maski logiczne

```python
a = np.arange(0, 80, 10)
mask = np.array([0, 1, 1, 0, 0, 1, 0, 0], dtype=bool)

b = a[mask]
print(a)
print(mask)
print(b)
```

### 📘 Teoria

Maski pozwalają filtrować dane.

---

## ✅ Operacje wzdłuż osi

```python
a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(a.sum())
print(a.sum(axis=0))
print(a.sum(axis=1))
print(np.max(a, axis=1))
print(np.argmax(a, axis=1))
print(np.mean(a, axis=0))
```
|
### 📘 Teoria

`axis=0` → kolumny
`axis=1` → wiersze

---

## ✅ np.where()

```python
a = np.arange(-2, 2) ** 2
mask = a % 2 == 0
b = np.where(mask)

print(a)
print(mask)
print(b)
```

### 📘 Teoria

`where` zwraca indeksy spełniające warunek.

---

## ✅ Iloczyn skalarny

```python
a = np.array([1, 0, 0, 1])
b = np.array([1, 2, 3, 4])

print(np.dot(a, b))
```

### 📘 Teoria

[ 1·1 + 0·2 + 0·3 + 1·4 = 5 ]

---

## ✅ Mnożenie macierzy

```python
a = np.array([[1, 0],
              [0, 1]])
b = np.array([[1, 2],
              [3, 4]])

print(np.dot(a, b))
```

### 📘 Teoria

Macierz jednostkowa nie zmienia wyniku.

---

## ✅ Transpozycja

```python
a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(a.T)
```

# 🔥 PyTorch – podstawy

```bash
pip install torch
```

```python
import torch
```
---

## ✅ Tworzenie tensorów

```python
tensor = torch.rand((3, 2))

print(type(tensor))
print(tensor.dtype)
print(tensor.shape)
print(tensor.device)
```

---

## ✅ CUDA (opcjonalnie)

```python
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print("Tensor przeniesiony na GPU")
```

---

## ✅ Indeksowanie tensorów

```python
points = torch.tensor([[4.0, 1.0],
                       [5.0, 3.0],
                       [2.0, 1.0]])

value = points[0, 1]
print(value)
print(value.item())
```

### 📘 Teoria

`.item()` konwertuje tensor → liczba Python.

---

## ✅ Łączenie tensorów

```python
t = torch.ones((4, 2))

t1 = torch.cat([t, t, t], dim=0)
t2 = torch.stack([t, t, t], dim=0)

print(t1.shape)
print(t2.shape)
```

### 📘 Teoria

* `cat` → doklejanie
* `stack` → nowy wymiar



# 🧠 Python list vs NumPy vs PyTorch

## 📌 Python list

✔ Struktura ogólnego przeznaczenia

✔ Może przechowywać różne typy danych

✔ Operacje wykonywane wolniej

✔ Brak operacji wektorowych

```python
lst = [1, 2, 3]
```

❗ Operacje są wykonywane element po elemencie w pętli (nawet jeśli tego nie widzimy).

---

## 📌 NumPy array

✔ Dane jednego typu (`dtype`)

✔ Bardzo szybkie obliczenia

✔ Operacje wektorowe (element‑wise)

✔ Idealne do obliczeń numerycznych

```python
arr = np.array([1, 2, 3])
```

✔ NumPy używa zoptymalizowanego kodu w C → duża wydajność.

---

## 📌 PyTorch Tensor

✔ Podobny do NumPy array

✔ Obsługa GPU

✔ Automatyczne różniczkowanie (gradienty)

✔ Fundament sieci neuronowych

```python
tensor = torch.tensor([1.0, 2.0, 3.0])
```

---

## ⚡ Kluczowe różnice

| Cecha              | Python list | NumPy         | PyTorch       |
| ------------------ | ----------- | ------------- | ------------- |
| Typ danych         | dowolne     | jednorodne    | jednorodne    |
| Szybkość           | wolna       | bardzo szybka | bardzo szybka |
| GPU                | ❌           | ❌             | ✔             |
| Operacje wektorowe | ❌           | ✔             | ✔             |
| Gradienty          | ❌           | ❌             | ✔             |

# 🧪 Mini‑eksperyment wydajnościowy

👉 Zadanie: Uruchom kod i porównaj czasy.

In [1]:
import time
import numpy as np
import torch

N = 10_000_000

print("Generowanie danych...")
lst = list(range(N))
arr = np.array(lst)
tensor_cpu = torch.tensor(lst)

# -------------------------
# Python list
# -------------------------
start = time.time()
_ = [x * 2 for x in lst]
print("Python list:", time.time() - start)

# -------------------------
# NumPy
# -------------------------
start = time.time()
_ = arr * 2
print("NumPy:", time.time() - start)

# -------------------------
# PyTorch CPU
# -------------------------
start = time.time()
_ = tensor_cpu * 2
print("PyTorch CPU:", time.time() - start)

# -------------------------
# PyTorch GPU
# -------------------------
if torch.cuda.is_available():
    print("\nTest GPU...")

    tensor_gpu = tensor_cpu.to('cuda')

    torch.cuda.synchronize()
    start = time.time()

    _ = tensor_gpu * 2

    torch.cuda.synchronize()
    print("PyTorch GPU:", time.time() - start)
else:
    print("\nGPU niedostępne")


Generowanie danych...
Python list: 0.6859903335571289
NumPy: 0.16457819938659668
PyTorch CPU: 0.035800933837890625

GPU niedostępne


## 🧠 Zadanie - analiza wydajności

👉 Porównaj czasy wykonywania kodu.

👉 Dlaczego różnice są tak duże?

👉 Dlaczego przy małych danych GPU może być wolniejsze?

# 🧩 Zadania – NumPy

### Zadanie 1 – Operacje element‑wise

Stwórz dwie tablice NumPy długości 5 z losowymi liczbami całkowitymi z zakresu 0–10. Następnie:

* oblicz sumę
* oblicz iloczyn
* podnieś pierwszą tablicę do potęgi drugiej
---

### Zadanie 2 – Slicing

Dana jest tablica:

```python
a = np.array([0,1,2,3,4,5,6,7,8,9])
```

Wyciągnij:

* tylko liczby parzyste używając slicing
* tablicę od końca co 2 elementy

---

### Zadanie 3 – Maski logiczne

Stwórz tablicę liczb od 0 do 20. Wybierz tylko liczby większe od 10.

---

### Zadanie 4 – Statystyki

Wygeneruj macierz 4×4 z liczbami losowymi. Oblicz:

* średnią całej macierzy
* średnią wierszy
* maksima kolumn

---

### Zadanie 5 – Widok vs kopia

Sprawdź eksperymentalnie różnicę między `.copy()` a slicingiem.


Zadanie 1

In [164]:
a = np.array([0,4,2,33,4,67,6,7,45,9])
b = np.array([1,5,7,83,32,0,78,71,5,2])

suma=a+b
iloczyn=a*b
potega=a*a
print("SUMA",suma)
print("ILOCZYN",iloczyn)
print("POTEGA",potega)


SUMA [  1   9   9 116  36  67  84  78  50  11]
ILOCZYN [   0   20   14 2739  128    0  468  497  225   18]
POTEGA [   0   16    4 1089   16 4489   36   49 2025   81]


Zadanie 2


In [34]:
c = np.array([0,1,2,3,4,5,6,7,8,9])
mask= c % 2 == 0
d=c[mask]
print(c[d])
print(c[2::2])
print(c[-1::-2])

[0 2 4 6 8]
[2 4 6 8]
[9 7 5 3 1]


Zadanie 3

In [39]:
d=np.arange(0,21)
mask=d-10>0
d[mask]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

Zadanie 4

In [55]:
e = np.array([[1, 2, 7, 3],[4, 6, 5, 7,],[7, 6, 7, 4,],[4, 4, 3, 2]])
print(e)
mean_e=e.mean()
print(mean_e)
print('---------------------------')
#ŚREDNIA WIERSZY 
print(np.mean(e, axis=1))
print('---------------------------')
#MAXIMA KOLUMN
print(np.max(e, axis=0))





[[1 2 7 3]
 [4 6 5 7]
 [7 6 7 4]
 [4 4 3 2]]
4.5
---------------------------
[3.25 5.5  6.   3.25]
---------------------------
[7 6 7 7]


Zadanie 5

In [70]:
#Copy tworzy osobny obiekt na którym można przeprowadzać zmiany bez naruszania oryginału 
#Użycie .copy()
a = np.array([0, 1, 2, 3, 4,5])
b= a.copy()
b = b[2:4]
b[0] = 10

print(a)
print(b)

#Bez .copy()
df = np.array([0, 1, 2, 3, 4, 5])
bf = df
bf = bf[2:4]
bf[0] = 10

print(df)
print(bf)


[0 1 2 3 4 5]
[10  3]
[ 0  1 10  3  4  5]
[10  3]


# 🔥 Zadania – PyTorch

### Zadanie 6 – Tensor losowy

Stwórz tensor 3×3 z liczbami losowymi. Oblicz:

* sumę
* średnią
* maksimum

---

### Zadanie 7 – Indeksowanie

Dla tensora:

```python
points = torch.rand((5, 2))
```

Wyciągnij:

* pierwszy wiersz
* drugą kolumnę
* element [2,1]

---

### Zadanie 8 – Operacje matematyczne

Wygeneruj tensor i policz:

* potęgę
* pierwiastek
* funkcję exp

---

### Zadanie 9 – cat vs stack

Sprawdź różnice wymiarów dla różnych wartości `dim`.

---

### Zadanie 10 – CUDA

Jeśli Google Colab - wystarczy zmienić typ środowiska wykonawczego na GPU-T4:

* przenieś tensor na GPU
* wykonaj operację
* wróć na CPU

# 🐛 Zadanie Debuggingowe 1 – Widok vs Kopia (NumPy)

### Kod:

```python
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = a[1:4]

b[0] = 999

print("a:", a)
print("b:", b)
```

---

### 🧠 Zadanie 11:

👉 Jaki będzie wynik?

👉 Dlaczego zmieniła się tablica `a`?

👉 Czy to jest bug czy feature NumPy?

👉 Jak naprawić kod, aby `a` się nie zmieniało?

In [157]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = a[1:4]

b[0] = 999

print("a:", a)
print("b:", b)

#Naprawione 

c = np.array([1, 2, 3, 4, 5])
d = c.copy()
d = d[1:4]

d[0] = 999

print("a:", c)
print("b:", d)

a: [  1 999   3   4   5]
b: [999   3   4]
a: [1 2 3 4 5]
b: [999   3   4]


# 🐛 Zadanie Debuggingowe 2 – CPU vs GPU (PyTorch)

### Kod:

```python
import torch

x = torch.rand((3, 3))
y = torch.rand((3, 3)).to('cuda')

z = x + y

print(z)
```

---

### 🧠 Zadanie 12:

👉 Czy kod zadziała?

👉 Jeśli nie – jaki błąd się pojawi?

👉 Dlaczego PyTorch nie „przeniesie automatycznie”?

👉 Jak poprawić kod?

In [ ]:
Kod nie zadziała 

In [161]:
import torch


x = torch.rand((3, 3))
y = torch.rand((3, 3))

z = x + y

print(z)

tensor([[1.2169, 0.3992, 1.0395],
        [0.7749, 1.2391, 0.9566],
        [1.2090, 0.9429, 1.2825]])



# 💀 Bonus
### Kod:

```python
import torch

x = torch.tensor([1, 2, 3])
y = torch.tensor([1.0, 2.0, 3.0])

z = x + y

print(z.dtype)
```

---

### 🧠 Zadanie 13:

👉 Jaki będzie dtype?

👉 Dlaczego?

👉 Dlaczego to ma znaczenie w sieciach neuronowych?

In [162]:
import torch

x = torch.tensor([1, 2, 3])
y = torch.tensor([1.0, 2.0, 3.0])

z = x + y

print(z.dtype)

torch.float32


In [ ]:
dtype będzie torch.float32
Tensor x ma typ int64, a tensor y ma typ float32.
Podczas wykonywania operacji PyTorch stosuje automatyczną promocję typów. Oznacza to, że gdy łączymy typ całkowity z typem zmiennoprzecinkowym, wynik zostaje zamieniony na float, aby nie utracić części dziesiętnej.
W sieciach neuronowych większość operacji wykorzystuje liczby zmiennoprzecinkowe (najczęściej float32)

# ✅ Podsumowanie

Po tych zajęciach student powinien:

* rozumieć różnicę ndarray vs tensor
* umieć indeksować i filtrować dane
* znać operacje axis / dim
* rozumieć podstawy GPU w PyTorch
  Po tych zajęciach student powinien:
* rozumieć różnicę ndarray vs tensor
* umieć indeksować i filtrować dane
* znać operacje axis / dim
* rozumieć podstawy używania GPU w PyTorch

Zad 7

In [77]:
tensor = torch.rand((3, 3))

print(type(tensor))
print(tensor.dtype)
print(tensor.shape)
print(tensor.device)

suma=tensor.sum()
mean=tensor.mean()
mx=tensor.max()
print(suma)
print(mean)
print(mx)

<class 'torch.Tensor'>
torch.float32
torch.Size([3, 3])
cpu
tensor(4.7235)
tensor(0.5248)
tensor(0.7594)


In [127]:
points = torch.rand((5, 2))

value=points[0:1]

print(points)



print(f"pierwszy wiersz",value)

print(f"pierwsza kolumna",points[:, 0])

print("Element:", points[2, 1])






tensor([[0.3506, 0.4137],
        [0.0902, 0.8929],
        [0.2491, 0.1271],
        [0.6208, 0.7677],
        [0.8738, 0.2666]])
pierwszy wiersz tensor([[0.3506, 0.4137]])
pierwsza kolumna tensor([0.3506, 0.0902, 0.2491, 0.6208, 0.8738])
Element: tensor(0.1271)


Zadanie 8 



In [135]:
t=torch.rand((3,3))

potega=t*t

sqrt=torch.sqrt(t)

exp= torch.exp(t)

print("Potega : ",potega)

print("Pierwiastek : ",sqrt)

print("Funkcja exp : ",exp)


Potega :  tensor([[0.9813, 0.1236, 0.0546],
        [0.9845, 0.0054, 0.1938],
        [0.5570, 0.5867, 0.9178]])
Pierwiastek :  tensor([[0.9953, 0.5930, 0.4833],
        [0.9961, 0.2713, 0.6635],
        [0.8639, 0.8752, 0.9788]])
Funkcja exp :  tensor([[2.6929, 1.4213, 1.2632],
        [2.6973, 1.0764, 1.5531],
        [2.1092, 2.1510, 2.6065]])


Zad 9 


In [147]:
t=torch.rand((3,3))
t1 = torch.cat([t, t, t], dim=0)
t2 = torch.stack([t, t, t], dim=1)

print(t1.shape)
print(t2.shape)

torch.Size([9, 3])
torch.Size([3, 3, 3])


In [143]:
print(t1)
print(t2)

tensor([[0.5268, 0.8013, 0.3095, 0.5268, 0.8013, 0.3095, 0.5268, 0.8013, 0.3095],
        [0.4430, 0.7963, 0.8193, 0.4430, 0.7963, 0.8193, 0.4430, 0.7963, 0.8193],
        [0.3776, 0.2290, 0.3137, 0.3776, 0.2290, 0.3137, 0.3776, 0.2290, 0.3137]])
tensor([[[0.5268, 0.8013, 0.3095],
         [0.5268, 0.8013, 0.3095],
         [0.5268, 0.8013, 0.3095]],

        [[0.4430, 0.7963, 0.8193],
         [0.4430, 0.7963, 0.8193],
         [0.4430, 0.7963, 0.8193]],

        [[0.3776, 0.2290, 0.3137],
         [0.3776, 0.2290, 0.3137],
         [0.3776, 0.2290, 0.3137]]])


Zadanie 10

In [149]:
import torch

tensor = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
print("Początkowy tensor (CPU):")
print(tensor)
print(tensor.device)

if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print("\nTensor przeniesiony na GPU:")
    print(tensor)
    print(tensor.device)

   
    tensor = tensor * 2
    print("\nTensor po operacji na GPU:")
    print(tensor)
    print(tensor.device)

    tensor = tensor.to('cpu')
    print("\nTensor wrócił na CPU:")
    print(tensor)
    print(tensor.device)
else:
    print("\nCUDA niedostępne. Operacje wykonujemy na CPU.")
    

Początkowy tensor (CPU):
tensor([[1., 2.],
        [3., 4.]])
cpu

CUDA niedostępne. Operacje wykonujemy na CPU.
